In [ ]:
#Referência & documentação
'https://numpy.org/doc/stable/reference/generated/numpy.array.html'

In [2]:
import numpy as np
from random import random

## Criando e acessando uma uma Array

In [3]:
#Array 1-Dimensão
array = np.array([2,1,6,5])

array[2]

6

In [4]:
#Array 1-Dimensão cheio de zeros
arr = np.zeros(5)
arr

array([0., 0., 0., 0., 0.])

In [5]:
#Array 5 linhas x 5 colunas cheio de zeros
zeros_mult = np.zeros((5,5))
print(zeros_mult.__repr__())
print('')

#Array cheio de 1's
ones_mult = np.ones((5,5))
print(ones_mult.__repr__())
print('')

#Array cheia de qualquer número
zeros_mult = np.full((5,5), 2.87)
print(zeros_mult.__repr__())

#Copiando uma array _like()
copy_mult = np.full_like(zeros_mult, random())
copy_mult

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

array([[2.87, 2.87, 2.87, 2.87, 2.87],
       [2.87, 2.87, 2.87, 2.87, 2.87],
       [2.87, 2.87, 2.87, 2.87, 2.87],
       [2.87, 2.87, 2.87, 2.87, 2.87],
       [2.87, 2.87, 2.87, 2.87, 2.87]])


array([[0.84464887, 0.84464887, 0.84464887, 0.84464887, 0.84464887],
       [0.84464887, 0.84464887, 0.84464887, 0.84464887, 0.84464887],
       [0.84464887, 0.84464887, 0.84464887, 0.84464887, 0.84464887],
       [0.84464887, 0.84464887, 0.84464887, 0.84464887, 0.84464887],
       [0.84464887, 0.84464887, 0.84464887, 0.84464887, 0.84464887]])

In [8]:
#Criando uma Array 4 linhas x 3 colunas
t = np.array(([0.55, 1.25, 0.82],
              [1, 2.25, 1.42],
              [0.82, 3.25, 1.85],
              [2, 3.35, 2.4]))

#Linha & coluna & elemento
t[0], t[:,0], t[2][2]

(array([0.55, 1.25, 0.82]), array([0.55, 1.  , 0.82, 2.  ]), 1.85)

In [7]:
#Array 1-Dimensão complexo
arr_complex = np.array([[0 + 1j, 2 + 3j, 1 + 0j], 
                        [5 + 2j, 1 + 3j, 0 + 2j]], dtype=complex)

#Mostrando Array
print(arr_complex.__repr__())

#Acessando elemento linha 0, coluna 1
print(arr_complex[0][1])

#Substituindo elemento
arr_complex[0,1] = 5 + 4j
arr_complex

array([[0.+1.j, 2.+3.j, 1.+0.j],
       [5.+2.j, 1.+3.j, 0.+2.j]])
(2+3j)


array([[0.+1.j, 5.+4.j, 1.+0.j],
       [5.+2.j, 1.+3.j, 0.+2.j]])

## Manipulando uma Array

### Mostrando 2 modos diferença de calcular uma função 

$$f(x) = x^2$$

In [48]:
%%time
#Caso 1 - +Fácil de entender/ler (alto reability), as custo de tempo de processamento

#Domínio
x = np.linspace(0, 10, 11)

#Declarar a array
uni_arr = np.empty(11)

#Calculando
uni_arr = x**2

uni_arr

Wall time: 0 ns


array([  0.,   1.,   4.,   9.,  16.,  25.,  36.,  49.,  64.,  81., 100.])

In [49]:
%%time
#Caso 2 - Visando performnace computacional, as custas de baixo 'reability'
x = np.linspace(0, 10, 11)
uni_arr = np.empty(11)

#Iterando para cada elemento
for index in range(len(uni_arr)):
    uni_arr[index] = x[index]**2
    
uni_arr

Wall time: 0 ns


array([  0.,   1.,   4.,   9.,  16.,  25.,  36.,  49.,  64.,  81., 100.])

In [20]:
#Criando uma Array 4 linhas x 3 colunas
Array = np.array(([0.55, 1.25, 0.82],
              [1, 2.25, 1.42],
              [0.82, 3.25, 1.85]))

for index, linha in enumerate(Array):
    print(f'{linha[1]} --- {linha[2]:.2f} --- {index} ')

1.25 --- 0.82 --- 0 
2.25 --- 1.42 --- 1 
3.25 --- 1.85 --- 2 


In [21]:
#Substituindo todas as linhas
for index in range(len(Array)):
    Array[index] = random()
Array

array([[0.08051817, 0.08051817, 0.08051817],
       [0.33602715, 0.33602715, 0.33602715],
       [0.41282191, 0.41282191, 0.41282191]])

In [22]:
#Substituindo todas as colunas
for index in range(len(Array)):
    Array[:,index] = random()
Array

array([[0.56362597, 0.9555362 , 0.24127862],
       [0.56362597, 0.9555362 , 0.24127862],
       [0.56362597, 0.9555362 , 0.24127862]])

In [23]:
#Substituindo elemento por elemento
for i in range(len(Array)):
    for j in range(len(Array)):
        Array[i][j] = random()
Array

array([[0.46662373, 0.58780533, 0.03625618],
       [0.93336284, 0.02051389, 0.41544409],
       [0.34135534, 0.52214854, 0.30228737]])

In [13]:
import numpy as np
Eq_1 = np.array([[-0.57, 1],
                 [-9.92, 1]])

Eq_2 = np.array([-(0.57**2), -(0.92**2)])

In [14]:
np.linalg.solve(Eq_1, Eq_2)

array([ 0.0557754 , -0.29310802])