In [2]:
from scipy.integrate import odeint
from scipy.integrate import quad, cumtrapz
from scipy.misc import derivative
import matplotlib.pyplot as plt
from sympy import *
import numpy as np
from sympy.abc import *
init_printing()

## Matrizes e transformação

In [3]:
er = symbols('e_{r}')
et = symbols('e_{\\theta}')
ez = symbols('e_{z}')

ex = symbols('e_{x}')
ey = symbols('e_{y}')
ez = symbols('e_{z}')

m_transf = Matrix([[cos(theta), sin(theta), 0], [-sin(theta),cos(theta), 0], [0, 0, 1]])
base_cilind = Matrix([er, et, ez])
base_xyz = Matrix([ex, ey, ez])

m_transf, m_transf.T

⎛⎡cos(θ)   sin(θ)  0⎤  ⎡cos(θ)  -sin(θ)  0⎤⎞
⎜⎢                  ⎥  ⎢                  ⎥⎟
⎜⎢-sin(θ)  cos(θ)  0⎥, ⎢sin(θ)  cos(θ)   0⎥⎟
⎜⎢                  ⎥  ⎢                  ⎥⎟
⎝⎣   0       0     1⎦  ⎣  0        0     1⎦⎠

In [4]:
base_cilind, base_xyz

⎛⎡  e_{r}   ⎤  ⎡e_{x}⎤⎞
⎜⎢          ⎥  ⎢     ⎥⎟
⎜⎢e_{\theta}⎥, ⎢e_{y}⎥⎟
⎜⎢          ⎥  ⎢     ⎥⎟
⎝⎣  e_{z}   ⎦  ⎣e_{z}⎦⎠

In [5]:
(Eq(base_cilind, m_transf*base_xyz, evaluate=False))

⎡  e_{r}   ⎤   ⎡e_{x}⋅cos(θ) + e_{y}⋅sin(θ) ⎤
⎢          ⎥   ⎢                            ⎥
⎢e_{\theta}⎥ = ⎢-e_{x}⋅sin(θ) + e_{y}⋅cos(θ)⎥
⎢          ⎥   ⎢                            ⎥
⎣  e_{z}   ⎦   ⎣           e_{z}            ⎦

## Tensores 

In [21]:
xx, xy, xz = symbols('\delta_{x} \delta_{xy} \delta_{xz}')
yx, yy, yz = symbols('\delta_{yx} \delta_{y} \delta_{yz}')
zx, zy, zz = symbols('\delta_{zx} \delta_{zy} \delta_{z}')

tensor_xyz = Array([[xx, xy, xz], [yx, yy, yz], [zx, zy, zz]])
Eq(tensor_xyz, 0)

⎡\delta_{x}   \delta_{xy}  \delta_{xz}⎤    
⎢                                     ⎥    
⎢\delta_{yx}  \delta_{y}   \delta_{yz}⎥ = 0
⎢                                     ⎥    
⎣\delta_{zx}  \delta_{zy}  \delta_{z} ⎦    

In [22]:
#tensor_cilind = tensorproduct(m_transf, tensor_xyz)
#tensor_cilind

In [23]:
import tensorflow as tf

In [24]:
tensor = tf.constant([[2,3],
                      [6,3]])
tensor, tensor.ndim

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[2, 3],
        [6, 3]])>,
 2)

In [25]:
tensor_1 = tf.constant([[2,3,1],
                        [6,3,8],
                        [6,3,0]])
tensor_1, tensor_1.ndim

(<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
 array([[2, 3, 1],
        [6, 3, 8],
        [6, 3, 0]])>,
 2)

In [26]:
tensor_2 = tf.constant([[[2,3,1],
                         [6,3,8],
                         [6,3,0]]])
tensor_2, tensor_2.ndim

(<tf.Tensor: shape=(1, 3, 3), dtype=int32, numpy=
 array([[[2, 3, 1],
         [6, 3, 8],
         [6, 3, 0]]])>,
 3)

## Séries de fourier 

In [16]:
from sympy.abc import *
#Olá 

s = fourier_series(x, (x ,-pi, pi))
s.scale(2).truncate(n=5)

In [8]:
s = fourier_series(1, (-pi, pi))
s

In [9]:
s = fourier_series(0, (-pi, pi))
s