# Roteiro do curso

1. Noções básicas e estruturas de dados (string, listas, dicionários)
2. *NumPy*(matemática numérica), *matplotlib*(gráficos) e *Pandas*(importação de dados)

## Tipo básicos de dados e operações 
1. inteiro (int), Racional (float) e caracteres (string)
2. soma (+), subtração (-), divisão (/), resto da divisão (//) e Exponencial (**)
3. Funções build-in - https://docs.python.org/3/library/functions.html

In [27]:
#Salvando um número em uma variável
a = 3           #int
c = 1.5         #float

d = 'Equipe'    #String
e = 'Zebra'     #String

In [28]:
#Operações com int e float
a+c

4.5

In [29]:
#Resultados separados por virgula
a-c, a/c, a//c, a**c

(1.5, 2.0, 2.0, 5.196152422706632)

In [30]:
#Operações com strings
d + e*2

'EquipeZebraZebra'

In [31]:
#Acesando um caractere de uma string
d = 'Equipe'
d[3], d[-1]

('i', 'e')

In [32]:
#Acesando um intervalo de caractere de uma string
#d[começo:fim]
d[0:3]

'Equ'

## Sequências de dados - Listas
1. https://docs.python.org/pt-br/3/tutorial/datastructures.html#more-on-lists

In [33]:
#Criando uma lista
lista = [1, 3, 5, 9, 6]
lista

[1, 3, 5, 9, 6]

In [34]:
#index - valor
lista[1]

3

In [35]:
#index - intervalo
lista[0:5]

[1, 3, 5, 9, 6]

In [36]:
#adicionar algum valor depois que criou
lista.append(40)
lista 

[1, 3, 5, 9, 6, 40]

Funções build-ins do python - https://docs.python.org/3/library/functions.html

In [37]:
sorted(lista, reverse=False)

[1, 3, 5, 6, 9, 40]

In [38]:
#Outras funções bulid-in
max(lista), min(lista), sum(lista), len(lista)

(40, 1, 64, 6)

## Sequências de dados - Dicionários

1. https://docs.python.org/pt-br/3/tutorial/datastructures.html#dictionaries

In [47]:
#Sequência {chave - valor}
dic = {'bala': 3, 'suco': [10, 2]}

In [48]:
#A partir da chave 'bala' resgatamos o preço
dic['suco']

[10, 2]

In [41]:
#Mostrando os as chaves 
print(dic.keys())

#Mostrando só os valores
print(dic.values())

dict_keys(['bala', 'suco'])
dict_values([3, 10])


## Controle de fluxo

# Funções

Na programação, **funções são blocos de código que realizam determinadas tarefas** que normalmente precisam ser executadas diversas vezes dentro de uma aplicação. Quando surge essa necessidade, para que várias **instruções não precisem ser repetidas**, elas são agrupadas em uma função, à qual é dado um nome e que poderá ser chamada/executada em diferentes partes do programa. 

In [42]:
#Criando uma função que soma dois numéros
def sub(valor_1, valor_2): #Argumentos da função
    
    #O que a função faz 
    resultado = valor_1 - valor_2
    
    return resultado #O que ela retorna

In [43]:
#Utilizando a função - colocando o nome dos argumentos
sub(valor_1=3, valor_2=7)

-4

In [44]:
#Utilizando a função - Por ordem dos argumetos
sub(3, 7)

-4

In [45]:
#Utilizando a função -  Por ordem dos argumetos
sub(7, 3)

4

In [46]:
#Salvando em uma variável
A = sub(7, 3)
A

4

## O que são módulos e bibliotecas ?
A **Biblioteca** em Python é uma **coleção de módulos de script** acessíveis a um programa Python para **simplificar o processo de programação** e remover a necessidade de reescrever os comandos mais usados. Eles podem ser usados chamando-os / importando-os no início de um script. De forma simplista, importar uma bilbioteca significa **usar os códigos de outras pessoas**. 

As principais bibliotecas em python são:
1. *Numpy*: https://numpy.org/doc/stable/index.html
2. *Matplotlib*: https://matplotlib.org/stable/users/index.html
3. *Pandas*: https://pandas.pydata.org/docs/user_guide/index.html

In [2]:
#Importando um biblioteca
import numpy as np

### NumPy - Arrays e operações aritméticas básicas

1. Opções para criar uma array - https://numpy.org/doc/stable/reference/routines.array-creation.html

In [20]:
#Criando uma array
lista = [10, 2, 9, 8]
arr = np.array(lista)

In [22]:
#Soma
arr + arr

array([20,  4, 18, 16])

In [ ]:
#Multiplicação
arr * arr

### NumPy - Operações não tão básicas

In [31]:
#Funções trigonométricas - cos(x)
np.cos(arr)

array([-0.83907153, -0.41614684, -0.91113026, -0.14550003])

In [30]:
#Funções logaritmicas - ln(x)
np.log(arr)

array([2.30258509, 0.69314718, 2.19722458, 2.07944154])

In [32]:
#Funções lógicas(booleanas)
arr > 2

array([ True, False,  True,  True])

In [36]:
import math 

math.log(2, 3)

0.6309297535714574

In [4]:
arr.sort()
arr

array([ 2,  8,  9, 10])

array([ 4, 16, 18, 20])